name: Wheel build

on:
  pull_request

jobs:
  build-wheel-windows-macos:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        python-architecture: [x86, x64]
        exclude:
          - os: macos-latest
            python-architecture: x86

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out the commit
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-architecture }}
    - name: Install prerequisites
      run: |
        python -m pip list
        python -m pip install --upgrade pip setuptools
        python -m pip install twine wheel
        python -m pip list
    - name: Build wheel
      run: |
        python -m pip wheel --no-deps -w ./dist .
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*.whl

  build-wheel-sdist-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the commit
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install prerequisites
      run: |
        python -m pip list
        python -m pip install --upgrade pip setuptools
        python -m pip install twine
        python -m pip list
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.3
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
    - name: Build sdist
      run: |
        python setup.py sdist
    - name: Publish wheels and sdist to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*-manylinux*.whl dist/*.tar.gz
